---
#
# Zuul Jobs Board configuration
#
# This file shall be located in the current working directory, where the app
# is running. Alternatively it can be kept as a hidden file (name preceded
# with a dot) in the app's user home directory.
#

#
# Application settings
#
app_port: 5333
db_file: 'zjb.sqlite3'
obsolete_days: 14
pull_interval: 21600  # 6 hours ~> pull 4 times a day


#
# Zuul API settings
#
api_url: 'https://zuul.example.com/api/'
api_tenant: 'tenant-name'


#
# Viewing options
#
# Specify lists of strings to filter for wanted results to fetch and display.
# When string starts and ends with forward slash (/), it is treated
# as a regular expression; otherwise an exact match of name is expected.
# Value of `None` instead of list = do not filter (i.e. display everything).
#
# NOTE: Branches *require* explicit names (not regular expressions)
#       due to limitations of Zuul API (see zuul.py:get_branches()).
#
views:
  MyView:
    pipelines:
      - check
    projects: ~  # None
    branches:
      master:
        - openstack-tox-pep8
        - /openstack-tox-py*/
      stable/wallaby:
        - openstack-tox-pep8
        - openstack-tox-py38


#
# Output groups
#
groups: ~
